version: '3.8'

networks:
  sandbox-nginx:
    driver: bridge

volumes:
  sandbox-nginx-mysql:
    driver: local

services:

  # ----------
  # nginx
  # ----------
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER}'
        WWWGROUP: '${WWWGROUP}'
    image: sandbox-nginx/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/usr/share/nginx/html
      - ./apps/frontend:/var/www/frontend
      - ./apps/backend:/var/www/backend
    networks:
      - sandbox-nginx

  # ----------
  # app - frontend
  # ----------
  frontend:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER}'
        WWWGROUP: '${WWWGROUP}'
    image: sandbox-nginx/app
    container_name: frontend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_FRONTEND_PORT:-8081}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - ./docker/php-fpm/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./apps/frontend:/var/www/frontend
    working_dir: /var/www/frontend
    networks:
      - sandbox-nginx
    depends_on:
      - nginx
      - db

  # ----------
  # app - backend
  # ----------
  backend:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER}'
        WWWGROUP: '${WWWGROUP}'
    image: sandbox-nginx/app
    container_name: backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_BACKEND_PORT:-8081}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - ./docker/php-fpm/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./apps/backend:/var/www/backend
    working_dir: /var/www/backend
    networks:
      - sandbox-nginx
    depends_on:
      - nginx
      - db

  # ----------
  # Database
  # ----------
  db:
    image: 'mysql/mysql-server:8.0'
    container_name: db
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sandbox-nginx-mysql:/var/lib/mysql'
    networks:
      - sandbox-nginx
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
